apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuphf-postgres
  labels:
    app: wuphf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wuphf
      tier: postgres
  template:
    metadata:
      labels:
        app: wuphf
        tier: postgres
    spec:
      tolerations:
      - key: "stateful"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - image: postgres:11
          name: postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                  secretKeyRef:
                    name: wuphf-secrets
                    key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wuphf-secrets
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-stateful-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-stateful-data
          persistentVolumeClaim:
            claimName: wuphf-postgres
