version: '3'
services:
    db:
        image: postgres:12
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    web:
        build: .
        image: rydercalmdown/wuphf
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DJANGO_SECRET_KEY=local
            - PYTHONUNBUFFERED=1
        volumes:
        - ./src/:/code
        ports:
        - "8000:8000"
        depends_on:
        - db
