# Generated by Django 3.0.6 on 2020-05-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuphf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wuphf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
